<?php
	//phpinfo();
	
	$servername = "localhost";
	$username = "root";
	$password = "";
	$dbname = "orc_db";
	
	$connection = new mysqli($servername, $username, $password, $dbname);
	$connection->set_charset("utf8");
	if($connection->connect_error){
		die("Connection failed: " . $connection->connect_error);
	}
	
	$old_sql = "INSERT INTO `contracts` (`id`, `id_document_contract`, `id_counterpartie_contract`, `number_pp`, `number_contract`, `name_work_contract`, `is_sip_contract`, `id_goz_contract`, `id_view_work_contract`, `all_count_contract`, `concluded_count_contract`, `amount_concluded_contract`, `formalization_count_contract`, `amount_formalization_contract`, `big_deal_contract`, `amoun_implementation_contract`, `comment_implementation_contract`, `prepayment_score_contract`, `invoice_score_contract`, `prepayment_payment_contract`, `amount_payment_contract`, `renouncement_contract`, `document_success_renouncement_reestr`, `number_aftair_renouncement_reestr`, `archive_contract`, `reconciliation_contract`, `date_contact`, `year_contract`, `created_at`, `updated_at`, `deleted_at`) VALUES
		(167, 22, 10, NULL, '124‐02‐2019', 'Для комплектующего элемента 2', 1, 2, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 0, NULL, NULL, 2019, '2019-04-18 07:18:28', '2019-05-23 05:15:50', NULL),
		(169, NULL, 10, NULL, '123‐01‐2020', 'Супер новый реестр криэйт', 0, 2, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 0, NULL, NULL, 2020, '2019-05-20 11:08:06', '2019-05-20 11:08:06', NULL);";
	//print($old_sql);
	
	$old_reestr = "INSERT INTO `reestr_contracts` (`id`, `id_contract_reestr`, `amount_contract_reestr`, `fix_amount_contract_reestr`, `big_deal_reestr`, `amount_invoice_reestr`, `selection_supplier_reestr`, `type_document_reestr`, `place_save_contract_reestr`, `date_save_contract_reestr`, `executor_contract_reestr`, `executor_reestr`, `oud_original_contract_reestr`, `otd_original_contract_reestr`, `date_contract_on_first_reestr`, `date_signing_contract_reestr`, `date_control_signing_contract_reestr`, `date_registration_project_reestr`, `date_signing_contract_counterpartie_reestr`, `date_entry_into_force_reestr`, `reconciliation_protocol_reestr`, `reconciliation_agreement_reestr`, `date_the_end_contract_reestr`, `number_inquiry_reestr`, `date_inquiry_reestr`, `number_answer_reestr`, `date_answer_reestr`, `days_reconciliation_reestr`, `count_mounth_reestr`, `begin_date_reconciliation_reestr`, `end_date_reconciliation_reestr`, `count_days_reconciliation_reestr`, `base_reestr`, `app_outgoing_number_reestr`, `app_incoming_number_reestr`, `result_second_department_date_reestr`, `result_second_department_number_reestr`, `marketing_reestr`, `marketing_goz_reestr`, `participation_reestr`, `marketing_fz_223_reestr`, `marketing_fz_44_reestr`, `procurement_reestr`, `single_provider_reestr`, `own_funds_reestr`, `investments_reestr`, `purchase_reestr`, `procurement_fz_223_reestr`, `procurement_fz_44_reestr`, `procurement_goz_reestr`, `other_reestr`, `mob_reestr`, `okpo_reestr`, `okved_reestr`, `number_contestants_reestr`, `denied_admission_reestr`, `cash_order_reestr`, `cash_contract_reestr`, `non_cash_order_reestr`, `non_cash_contract_reestr`, `date_execution_reestr`, `number_counterpartie_contract_reestr`, `igk_reestr`, `ikz_reestr`, `okdp_reestr`, `okpd_2_reestr`, `date_bank_reestr`, `amount_bank_reestr`, `bank_reestr`, `date_b_contract_reestr`, `date_e_contract_reestr`, `date_contract_reestr`, `date_maturity_date_reestr`, `date_maturity_reestr`, `amount_reestr`, `unit_reestr`, `vat_reestr`, `economy_reestr`, `economy_unit_reestr`, `amount_comment_reestr`, `prepayment_order_reestr`, `score_order_reestr`, `payment_order_reestr`, `prolongation_reestr`, `re_registration_reestr`, `created_at`, `updated_at`) VALUES
		(17, 170, '123456789', 0, 0, '1724323', 2, 1, 'Отдел 31', '21.05.2019', 'Исполнитель 1', '1', NULL, NULL, '27.05.2019', '29.05.2019', '26.05.2019', '28.05.2019', '30.05.2019', '19.05.2019', 1, 2, NULL, '17894512578127834', '21.05.2019', '78928736817678234', '22.05.2019', '20 дней', '7', '06.05.2019', '09.05.2019', '74', NULL, 'Заявка с исходящим таким-то!', 'Входящий номерок!', '22.05.2019', 'Номерочек', 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '46816812468441263152146812436112', '123465784', '1232434537', NULL, 'ОКПД 2 дада именно он!', '21.05.2019', '1265188', '16548651684', '08.05.2019', '23.05.2019', '41681681684165416513513', NULL, 'Нужно все выполнить до 7 ноября 2020', '12135181', 1, 1, '68166', 2, 'Ого! Как же это выгодно!', '30% аванса', 'Всё заплатили и никаких проблем!', 'Тут содержится иная информация!', NULL, NULL, '2019-05-27 08:41:53', '2019-05-27 08:50:19');";
	//print($old_reestr);
	
	$new_sql = "INSERT INTO `contracts` (`id`, `id_document_contract`, `id_counterpartie_contract`, `number_pp`, `number_contract`, `name_work_contract`, `is_sip_contract`, `id_goz_contract`, `id_view_work_contract`, `all_count_contract`, `concluded_count_contract`, `amount_concluded_contract`, `formalization_count_contract`, `amount_formalization_contract`, `big_deal_contract`, `amoun_implementation_contract`, `comment_implementation_contract`, `prepayment_score_contract`, `invoice_score_contract`, `prepayment_payment_contract`, `amount_payment_contract`, `renouncement_contract`, `document_success_renouncement_reestr`, `number_aftair_renouncement_reestr`, `archive_contract`, `reconciliation_contract`, `date_contact`, `year_contract`, `created_at`, `updated_at`, `deleted_at`) VALUES";
	$new_sql_reestr = "INSERT INTO `reestr_contracts` (`id`, `id_contract_reestr`, `amount_contract_reestr`, `fix_amount_contract_reestr`, `big_deal_reestr`, `amount_invoice_reestr`, `selection_supplier_reestr`, `type_document_reestr`, `place_save_contract_reestr`, `date_save_contract_reestr`, `executor_contract_reestr`, `executor_reestr`, `oud_original_contract_reestr`, `otd_original_contract_reestr`, `date_contract_on_first_reestr`, `date_signing_contract_reestr`, `date_control_signing_contract_reestr`, `date_registration_project_reestr`, `date_signing_contract_counterpartie_reestr`, `date_entry_into_force_reestr`, `reconciliation_protocol_reestr`, `reconciliation_agreement_reestr`, `date_the_end_contract_reestr`, `number_inquiry_reestr`, `date_inquiry_reestr`, `number_answer_reestr`, `date_answer_reestr`, `days_reconciliation_reestr`, `count_mounth_reestr`, `begin_date_reconciliation_reestr`, `end_date_reconciliation_reestr`, `count_days_reconciliation_reestr`, `base_reestr`, `app_outgoing_number_reestr`, `app_incoming_number_reestr`, `result_second_department_date_reestr`, `result_second_department_number_reestr`, `marketing_reestr`, `marketing_goz_reestr`, `participation_reestr`, `marketing_fz_223_reestr`, `marketing_fz_44_reestr`, `procurement_reestr`, `single_provider_reestr`, `own_funds_reestr`, `investments_reestr`, `purchase_reestr`, `procurement_fz_223_reestr`, `procurement_fz_44_reestr`, `procurement_goz_reestr`, `other_reestr`, `mob_reestr`, `okpo_reestr`, `okved_reestr`, `number_contestants_reestr`, `denied_admission_reestr`, `cash_order_reestr`, `cash_contract_reestr`, `non_cash_order_reestr`, `non_cash_contract_reestr`, `date_execution_reestr`, `number_counterpartie_contract_reestr`, `igk_reestr`, `ikz_reestr`, `okdp_reestr`, `okpd_2_reestr`, `date_bank_reestr`, `amount_bank_reestr`, `bank_reestr`, `date_b_contract_reestr`, `date_e_contract_reestr`, `date_contract_reestr`, `date_maturity_date_reestr`, `date_maturity_reestr`, `amount_reestr`, `unit_reestr`, `vat_reestr`, `economy_reestr`, `economy_unit_reestr`, `amount_comment_reestr`, `prepayment_order_reestr`, `score_order_reestr`, `payment_order_reestr`, `prolongation_reestr`, `re_registration_reestr`, `created_at`, `updated_at`) VALUES";
	
	$new_id = 47860;
	$new_id_reestr = 47704;
	for($i=0;$i<1;$i++)
	{
		//Контракты
		$id_counterpartie = rand(1,63);
		$id_view_work = rand(1,7);
		$new_sql = "INSERT INTO `contracts` (`id`, `id_document_contract`, `id_counterpartie_contract`, `number_pp`, `number_contract`, `name_work_contract`, `is_sip_contract`, `id_goz_contract`, `id_view_work_contract`, `all_count_contract`, `concluded_count_contract`, `amount_concluded_contract`, `formalization_count_contract`, `amount_formalization_contract`, `big_deal_contract`, `amoun_implementation_contract`, `comment_implementation_contract`, `prepayment_score_contract`, `invoice_score_contract`, `prepayment_payment_contract`, `amount_payment_contract`, `renouncement_contract`, `document_success_renouncement_reestr`, `number_aftair_renouncement_reestr`, `archive_contract`, `reconciliation_contract`, `date_contact`, `year_contract`, `created_at`, `updated_at`, `deleted_at`) VALUES
						($new_id, NULL, $id_counterpartie, $new_id, '" . $new_id . "‐01‐2019', 'Это новый динамичный контракт с id $new_id', 0, 1, $id_view_work, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 0, NULL, NULL, 2020, '2019-05-27 14:09:01', '2019-05-27 14:09:01', NULL);";
		
		
		//Реестр
		$id_selection_suppliers = rand(1,7);
		$id_type_document = rand(1,5);
		$new_sql_reestr = "INSERT INTO `reestr_contracts` (`id`, `id_contract_reestr`, `amount_contract_reestr`, `fix_amount_contract_reestr`, `big_deal_reestr`, `amount_invoice_reestr`, `selection_supplier_reestr`, `type_document_reestr`, `place_save_contract_reestr`, `date_save_contract_reestr`, `executor_contract_reestr`, `executor_reestr`, `oud_original_contract_reestr`, `otd_original_contract_reestr`, `date_contract_on_first_reestr`, `date_signing_contract_reestr`, `date_control_signing_contract_reestr`, `date_registration_project_reestr`, `date_signing_contract_counterpartie_reestr`, `date_entry_into_force_reestr`, `reconciliation_protocol_reestr`, `reconciliation_agreement_reestr`, `date_the_end_contract_reestr`, `number_inquiry_reestr`, `date_inquiry_reestr`, `number_answer_reestr`, `date_answer_reestr`, `days_reconciliation_reestr`, `count_mounth_reestr`, `begin_date_reconciliation_reestr`, `end_date_reconciliation_reestr`, `count_days_reconciliation_reestr`, `base_reestr`, `app_outgoing_number_reestr`, `app_incoming_number_reestr`, `result_second_department_date_reestr`, `result_second_department_number_reestr`, `marketing_reestr`, `marketing_goz_reestr`, `participation_reestr`, `marketing_fz_223_reestr`, `marketing_fz_44_reestr`, `procurement_reestr`, `single_provider_reestr`, `own_funds_reestr`, `investments_reestr`, `purchase_reestr`, `procurement_fz_223_reestr`, `procurement_fz_44_reestr`, `procurement_goz_reestr`, `other_reestr`, `mob_reestr`, `okpo_reestr`, `okved_reestr`, `number_contestants_reestr`, `denied_admission_reestr`, `cash_order_reestr`, `cash_contract_reestr`, `non_cash_order_reestr`, `non_cash_contract_reestr`, `date_execution_reestr`, `number_counterpartie_contract_reestr`, `igk_reestr`, `ikz_reestr`, `okdp_reestr`, `okpd_2_reestr`, `date_bank_reestr`, `amount_bank_reestr`, `bank_reestr`, `date_b_contract_reestr`, `date_e_contract_reestr`, `date_contract_reestr`, `date_maturity_date_reestr`, `date_maturity_reestr`, `amount_reestr`, `unit_reestr`, `vat_reestr`, `economy_reestr`, `economy_unit_reestr`, `amount_comment_reestr`, `prepayment_order_reestr`, `score_order_reestr`, `payment_order_reestr`, `prolongation_reestr`, `re_registration_reestr`, `created_at`, `updated_at`) VALUES
							($new_id_reestr, $new_id, '123456789', 0, 0, '1724323', $id_selection_suppliers, $id_type_document, 'Отдел 31', '21.05.2019', 'Исполнитель', '1', NULL, NULL, '27.05.2019', '29.05.2019', '26.05.2019', '28.05.2019', '30.05.2019', '19.05.2019', " . rand(1,2) . ", " . rand(1,2) . ", NULL, '17894512578127834', '21.05.2019', '78928736817678234', '22.05.2019', '20 дней', '7', '06.05.2019', '09.05.2019', '74', NULL, 'Заявка с исходящим таким-то!', 'Входящий номерок!', '22.05.2019', 'Номерочек', " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '46816812468441263152146812436112', '123465784', '1232434537', NULL, 'ОКПД 2 дада именно он!', '21.05.2019', '1265188', '16548651684', '08.05.2019', '23.05.2019', '41681681684165416513513', NULL, 'Нужно все выполнить до 7 ноября 2020', '12135181', 1, 1, '68166', 2, 'Ого! Как же это выгодно!', '30% аванса', 'Всё заплатили и никаких проблем!', 'Тут содержится иная информация!', NULL, NULL, '2019-05-27 15:03:53', '2019-05-27 15:03:53');";
		
		//Запросы
		//$connection->query($new_sql);
		//$connection->query($new_sql_reestr);
		
		/*if($connection->query($new_sql) === TRUE)
			echo "New record add<br/>";
		else
			echo "Error: " . $new_sql . "<br/>" . $connection->error;
			
		if($connection->query($new_sql_reestr) === TRUE)
			echo "New record add<br/>";
		else
			echo "Error: " . $new_sql_reestr . "<br/>" . $connection->error;*/
		
		$new_id++;
		$new_id_reestr++;
	}
	
	echo 'Следующий id: ' . $new_id . '<br/>';
	echo 'Следующий id реестра: ' . $new_id_reestr;
	//$new_sql .= "($new_id, NULL, $id_counterpartie, $new_id, '" . $new_id . "‐01‐2019', 'Это новый динамичный контракт с id $new_id', 0, 1, $id_view_work, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 0, NULL, NULL, 2020, '2019-05-27 14:09:01', '2019-05-27 14:09:01', NULL);";
	
	//$new_sql_reestr .= "($new_id_reestr, $new_id, '123456789', 0, 0, '1724323', $id_selection_suppliers, $id_type_document, 'Отдел 31', '21.05.2019', 'Исполнитель', '1', NULL, NULL, '27.05.2019', '29.05.2019', '26.05.2019', '28.05.2019', '30.05.2019', '19.05.2019', " . rand(1,2) . ", " . rand(1,2) . ", NULL, '17894512578127834', '21.05.2019', '78928736817678234', '22.05.2019', '20 дней', '7', '06.05.2019', '09.05.2019', '74', NULL, 'Заявка с исходящим таким-то!', 'Входящий номерок!', '22.05.2019', 'Номерочек', " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", " . rand(0,1) . ", NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '46816812468441263152146812436112', '123465784', '1232434537', NULL, 'ОКПД 2 дада именно он!', '21.05.2019', '1265188', '16548651684', '08.05.2019', '23.05.2019', '41681681684165416513513', NULL, 'Нужно все выполнить до 7 ноября 2020', '12135181', 1, 1, '68166', 2, 'Ого! Как же это выгодно!', '30% аванса', 'Всё заплатили и никаких проблем!', 'Тут содержится иная информация!', NULL, NULL, '2019-05-27 15:03:53', '2019-05-27 15:03:53');";
	//print($new_sql);
	//print($new_sql_reestr);
	
	$connection->close();
?>